### ISSUE TITLE
Move block up in order

### ISSUE THREAD

**Issue by ksolomon** [AmedeeBulle/StatusLine#1]
I was wondering how tough it would be to move the block above the Files section.  Seems like a more useful position for it, since when it's being used, the Files section generally isn't.

**Comment by AmedeeBulle** [comment]
I **think** OctoPrint doesn't allows it, but I need to double check.
It annoys me as well, I usually fold the file list to see the messages at a reasonable place...

**Comment by AmedeeBulle** [comment]
From http://docs.octoprint.org/en/master/plugins/mixins.html#templateplugin
> Note that with the current implementations, plugins will always be located beneath the existing sections.

So this is not something I can fix...
